---
layout: cv
title: Opeyemi's CV
---
# Opeyemi Oyebanji
Analyst, Business, COnsultant.

<div id="webaddress">
<a href="Oye20004@byui.edu">
| <a href="oyebanjiopeyemio@gmail.com">My gmail</a>
</div>


## Currently

A Business Analytics major student at Brigham Young University - Idaho, with a passion for data analysis and problem-solving.

### Skills
Microsoft Office, Time Management, Public Relations, Customer Service, Team and Collaboration, Problem-Solving, Organization and Record-Keeping



## Education

`Jan 2023 - Present`
__Brigham Young University – Idaho Rexburg, Idaho__
Bachelor of Science in Business Analytics 

`Feb 2021`
__Aeroport College of Aviation and Travel Management Nigeria__

- Customer Service Specialist Certificate /

## Work Experience
`Mar 2023 – Present`
__Library Aide__, McKay Library, Brigham Young University, Idaho Rexburg, Idaho

- Facilitate the efficient acquisition, evaluation, and organization of library resources for patrons, managing a 
diverse collection exceeding 100,000 volumes and periodicals. 
- Collaborate closely with a team of 30+ aides and librarians to cultivate an environment conducive to academic 
inquiry and research for patrons and faculty.
- Maintain library organization by arranging materials according to the Library of Congress system, improving search 
accessibility.

`Jan 2022 – Nov 2022`
__Educational Travel Consultant__, Nigeria

- Delivered personalized educational consultation services, addressing inquiries, and resolving concerns for a 
clientele exceeding 10 individuals.
- Provided expert guidance to students regarding study prerequisites through diverse social platforms, resulting in 
a 5% increase in follower engagement.
- Demonstrated a commitment to responsiveness and problem-solving, ensuring timely resolution of customer 
needs.
- Proactively pursued ongoing professional development initiatives, enhancing company efficiency by 5%.

`Nov 2017 – June 2019`
__VOLUNTEER EXPERIENCE__, Voluntary Missionary Service, The Church of Jesus Christ of Latter-day Saints Benin City, Nigeria

- Strategically planned and executed daily and weekly goals, transforming objectives into actionable initiatives.
- Maintained accurate daily records essential for future reference and reporting purposes.
- Led and supported a team of 5+ missionaries, promoting motivation, assessing progress, and ensuring well-being.



<!-- ### Footer

Last updated: December 2024 -->